#!/bin/sh

ENABLED=yes
PROCS="v2ray"
ARGS=" &"
PREARGS=""
DESC=$PROCS
PATH=/opt/home/v2ray-linux-arm:/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

[ -z "$(which $PROCS)" ] && exit 0

. /opt/etc/init.d/rc.func
